# Site settings
title:     左子祯 - 全栈设计师 | 独立开发者
email:     hjsfzzz@gmail.com
description: "我是左子祯，一个爱好广泛的全栈设计师和独立开发者"
keywords: "左子祯, zizhen, zizhen zuo, zizhenzuo, china designer"
author:   "Zizhen Zuo"
url: "https://zizhenzuo.com"
baseurl: ""
name: zizhen

# # SCSS settings
# sass:
#   sass_dir: assets/stylesheets/_libs

# SNS settings
RSS: ture
dribbble_username:  zuonx
behance_username:   zuonx
pinterest_username: zuozizhen
github_username:    zuonx
instagram_username: zuozizhen
zhihu_username:     ZiJen

# Paginate settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 7
paginate_path: "blog/page:num"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true

# plugins
plugins: 
  - jekyll-paginate

stylus:
  compress: true
  path: assets/stylesheets

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# Analytics settings

ga_track_id: 'UA-139603337-1'

# #fixbug
# exclude: vendor

# jekyll-pug:
#   shipped_version: 2.0.0-beta10
